= Zeiterfassung für Gruppe 10

Notieren Sie die Zeit in Minuten für jeden Entwickler und – getrennt davon – für Team-Treffen pro Woche (Wochengranularität).
Die individuell erfasste Zeit beinhaltet auch das Lesen von Dokumentationen, Besprechungen mit Teamkollegen und sonstige auf das Praktikum bezogene Aufgaben, jedoch *nicht* das Team-Treffen (= letzte Spalte).

// See http://asciidoctor.org/docs/user-manual/#tables
[option="headers"]
|===
|Woche |Tobias|Max |Michelle |Oleksandr |Gabriela |Lukas |Matti |Dev8 |Meeting
|1  |1.5h |3.5h    |1h  |2    |1h   |1h    |1h    |…    |0.75h
|2  |2h |5h    |5h |5    |2,5h    |1h    |5,5h    |…    |1.5h
|3  |2h  |4h    |4h   |…    |3h    |3h    |5h    |…    |1.5h
|4  |7h  |6.5h    |6.5h    |…    |4h    |…    |6h    |…    |4h
|5  |…   |…    |…    |…    |4h    |…  |…    |…    |…
|6  |…   |…    |…    |…    |…    |…    |…    |…    |…
|7  |…   |…    |…    |…    |…    |…    |…    |…    |…
|8  |…   |…    |…    |…    |…    |…    |…    |…    |…
|9  |…   |…    |…    |…    |…    |…    |…    |…    |…
|10  |…   |…    |…    |…    |…    |…    |…    |…    |…
|11  |…   |…    |…    |…    |…    |…    |…    |…    |…
|12  |…   |…    |…    |…    |…    |…    |…    |…    |…
|===

Bitte tragen Sie am Ende des Praktikums noch folgende weitere Werte ein:
Summe der Arbeitsstunden pro Student:

SUMME(SPALTE(DevX))

Arbeitsstunden pro Woche pro Student:

SUMME(SPALTE(DevX)) / 12

Durchschnittliche Arbeitzeit aller Studenten pro Woche:

(SUMME(SPALTE(Dev1)) + SUMME(SPALTE(Dev2)) + SUMME(SPALTE(Dev3)) + SUMME(SPALTE(Dev4)) + SUMME(SPALTE(Dev5)) +SUMME(SPALTE(Dev6))) / 6
